apiVersion: mysql.oracle.com/v2alpha1 
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  instances: 3
  version: "8.0.24"
  imagePullPolicy: Always 
  imagePullSecrets:
    - name: ivanma-secret-mysql-operator
  router:
    instances: 1 
    version: "8.0.24" 
    spec:
      imagePullSecrets:
        - name: ivanma-secret-mysql-operator
  secretName: mypwds
