apiVersion: v1
kind: Service
metadata:
  name: nodetestapp-svc
  labels:
    app: nodetestapp-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8181
  selector:
    app: nodetestapp-pod
