apiVersion: v1
kind: Service
metadata:
  name: nodetestapp-svc
  labels:
    app: nodetestapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007
  selector:
    app: nodetestapp-service
