---
apiVersion: v1
kind: Pod
metadata:
  name: phpmyadmin
  labels:
    name: phpmyadmin
spec:
  containers:
    - name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      env:
        - name: PMA_HOST
          value: "mycluster"
        - name: PMA_PORT
          value: "6446"
      ports:
        - containerPort: 80
          name: phpmyadmin
