apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mycluster
spec:
  instances: 3
  secretName: mypwds
  baseServerId: 2000
  imagePullSecrets: 
  - name: mydockersecret
  router:
    instances: 3
  mycnf: |
    [mysqld]
    default-time-zone="+08:00"
    general-log=1
  datadirVolumeClaimTemplate:
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi


