apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mycluster-0
spec:
  storageClassName: oci
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mycluster-1
spec:
  storageClassName: oci
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mycluster-2
spec:
  storageClassName: oci
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
